Below is a demonstration of a preliminary analysis using the NCDS dataset using sweeps 16 and 23 (1974-1981). The following reflects on the initial school-to-work transition, number of o-level passes.

In [1]:
import stata_setup

stata_setup.config("E:\Stata SE", "se")

  ___  ____  ____  ____  ____ ®
 /__    /   ____/   /   ____/      17.0
___/   /   /___/   /   /___/       SE—Standard Edition

 Statistics and Data Science       Copyright 1985-2021 StataCorp LLC
                                   StataCorp
                                   4905 Lakeway Drive
                                   College Station, Texas 77845 USA
                                   800-STATA-PC        https://www.stata.com
                                   979-696-4600        stata@stata.com

Stata license: Unlimited-user network, expiring 14 Sep 2022
Serial number: 401709309008
  Licensed to: Scott Oatley
               University of Edinburgh

Notes:
      1. Unicode is supported; see help unicode_advice.
      2. Maximum number of variables is set to 5,000; see help set_maxvar.

In [2]:
%%stata

use "C:\Users\scott\Desktop\Stata data and do\NCDS\NCDS Sweep 16\stata\stata11\ncds0123.dta"

.
. use "C:\Users\scott\Desktop\Stata data and do\NCDS\NCDS Sweep 16\stata\stata1
> 1\ncds0123.dta"

.

In order to use both sweeps I'll need to merge them into one dataset. First I locate and set the root to the correct folder that has the 23 sweep in, then I merge the 16 and 23 sweeps.

In [3]:
 %%stata
 cd "C:\Users\scott\Desktop\Stata data and do\NCDS\NCDS Sweep 23\stata\stata9"
 
 merge 1:1 ncdsid using ncds4
 drop _merge

. cd "C:\Users\scott\Desktop\Stata data and do\NCDS\NCDS Sweep 23\stata\stata9"
C:\Users\scott\Desktop\Stata data and do\NCDS\NCDS Sweep 23\stata\stata9

.
. merge 1:1 ncdsid using ncds4

    Result                      Number of obs
    -----------------------------------------
    Not matched                         6,021
        from master                     6,021  (_merge==1)
        from using                          0  (_merge==2)

    Matched                            12,537  (_merge==3)
    -----------------------------------------

. drop _merge

.

Before any regressions or advanced statistical techniques, I'm going to reflect upon the economic activity of individuals within this dataset. For that I'll be looking at the 23 sweep where those individuals would have left compulsory schooling.

In [4]:
%%stata

gen econ194=.
replace econ194=. if (ec194==-1)
replace econ194=1 if (ec194==100)
replace econ194=1 if (ec194==101)
replace econ194=1 if (ec194==110)
replace econ194=1 if (ec194==120)
replace econ194=1 if (ec194==140)
replace econ194=1 if (ec194==150)
replace econ194=2 if (ec194==200)
replace econ194=3 if (ec194==500)
replace econ194=4 if (ec194==550)
replace econ194=5 if (ec194==600)
replace econ194=6 if (ec194==700)

label define econactivity_lbl 1"Full Time Employment" 2"Part Time Employment" 3"Education" 4"School" 5"Unemployment" 6"Out of Labour Force"
label value econ194 econactivity_lbl

tab econ194

gen econ195=.
replace econ195=. if (ec195==-1)
replace econ195=1 if (ec195==100)
replace econ195=1 if (ec195==101)
replace econ195=1 if (ec195==110)
replace econ195=1 if (ec195==120)
replace econ195=1 if (ec195==140)
replace econ195=1 if (ec195==150)
replace econ195=1 if (ec195==152)
replace econ195=2 if (ec195==200)
replace econ195=3 if (ec195==500)
replace econ195=4 if (ec195==550)
replace econ195=5 if (ec195==600)
replace econ195=6 if (ec195==700)

label value econ195 econactivity_lbl

tab econ195

gen econ196=.
replace econ196=. if (ec196==-1)
replace econ196=1 if (ec196==100)
replace econ196=1 if (ec196==101)
replace econ196=1 if (ec196==110)
replace econ196=1 if (ec196==111)
replace econ196=1 if (ec196==113)
replace econ196=1 if (ec196==120)
replace econ196=1 if (ec196==140)
replace econ196=1 if (ec196==150)
replace econ196=1 if (ec196==152)
replace econ196=2 if (ec196==200)
replace econ196=2 if (ec196==240)
replace econ196=3 if (ec196==500)
replace econ196=4 if (ec196==550)
replace econ196=5 if (ec196==600)
replace econ196=5 if (ec196==602)
replace econ196=6 if (ec196==700)
replace econ196=3 if (ec196==800)

label value econ196 econactivity_lbl

tab econ196

gen econ197=.
replace econ197=. if (ec197==-1)
replace econ197=1 if (ec197==100)
replace econ197=1 if (ec197==101)
replace econ197=1 if (ec197==110)
replace econ197=1 if (ec197==111)
replace econ197=1 if (ec197==113)
replace econ197=1 if (ec197==120)
replace econ197=1 if (ec197==140)
replace econ197=1 if (ec197==150)
replace econ197=1 if (ec197==152)
replace econ197=2 if (ec197==200)
replace econ197=2 if (ec197==240)
replace econ197=3 if (ec197==500)
replace econ197=4 if (ec197==550)
replace econ197=5 if (ec197==600)
replace econ197=5 if (ec197==602)
replace econ197=6 if (ec197==700)
replace econ197=6 if (ec197==701)
replace econ197=3 if (ec197==800)

label value econ197 econactivity_lbl

tab econ197

gen econ198=.
replace econ198=. if (ec198==-1)
replace econ198=1 if (ec198==100)
replace econ198=1 if (ec198==101)
replace econ198=1 if (ec198==110)
replace econ198=1 if (ec198==111)
replace econ198=1 if (ec198==113)
replace econ198=1 if (ec198==114)
replace econ198=1 if (ec198==120)
replace econ198=1 if (ec198==121)
replace econ198=1 if (ec198==130)
replace econ198=1 if (ec198==140)
replace econ198=1 if (ec198==150)
replace econ198=1 if (ec198==152)
replace econ198=2 if (ec198==200)
replace econ198=2 if (ec198==201)
replace econ198=2 if (ec198==220)
replace econ198=6 if (ec198==300)
replace econ198=6 if (ec198==400)
replace econ198=3 if (ec198==500)
replace econ198=4 if (ec198==550)
replace econ198=5 if (ec198==600)
replace econ198=5 if (ec198==601)
replace econ198=5 if (ec198==602)
replace econ198=6 if (ec198==700)
replace econ198=6 if (ec198==701)
replace econ198=3 if (ec198==800)

label value econ198 econactivity_lbl

tab econ198

gen econ199=.
replace econ199=. if (ec199==-1)
replace econ199=1 if (ec199==100)
replace econ199=1 if (ec199==101)
replace econ199=1 if (ec199==110)
replace econ199=1 if (ec199==111)
replace econ199=1 if (ec199==113)
replace econ199=1 if (ec199==114)
replace econ199=1 if (ec199==120)
replace econ199=1 if (ec199==121)
replace econ199=1 if (ec199==130)
replace econ199=1 if (ec199==131)
replace econ199=1 if (ec199==140)
replace econ199=1 if (ec199==150)
replace econ199=1 if (ec199==152)
replace econ199=2 if (ec199==200)
replace econ199=2 if (ec199==201)
replace econ199=2 if (ec199==220)
replace econ199=6 if (ec199==300)
replace econ199=6 if (ec199==400)
replace econ199=3 if (ec199==500)
replace econ199=4 if (ec199==550)
replace econ199=5 if (ec199==600)
replace econ199=5 if (ec199==601)
replace econ199=5 if (ec199==602)
replace econ199=6 if (ec199==700)
replace econ199=6 if (ec199==701)
replace econ199=3 if (ec199==800)

label value econ199 econactivity_lbl

tab econ199

gen econ200=.
replace econ200=. if (ec200==-1)
replace econ200=1 if (ec200==100)
replace econ200=1 if (ec200==101)
replace econ200=1 if (ec200==110)
replace econ200=1 if (ec200==111)
replace econ200=1 if (ec200==113)
replace econ200=1 if (ec200==114)
replace econ200=1 if (ec200==120)
replace econ200=1 if (ec200==121)
replace econ200=1 if (ec200==130)
replace econ200=1 if (ec200==131)
replace econ200=1 if (ec200==140)
replace econ200=1 if (ec200==141)
replace econ200=1 if (ec200==150)
replace econ200=1 if (ec200==152)
replace econ200=2 if (ec200==200)
replace econ200=2 if (ec200==201)
replace econ200=2 if (ec200==220)
replace econ200=6 if (ec200==300)
replace econ200=6 if (ec200==400)
replace econ200=3 if (ec200==500)
replace econ200=4 if (ec200==550)
replace econ200=5 if (ec200==600)
replace econ200=5 if (ec200==601)
replace econ200=5 if (ec200==602)
replace econ200=6 if (ec200==700)
replace econ200=6 if (ec200==701)
replace econ200=3 if (ec200==800)

label value econ200 econactivity_lbl

tab econ200

gen econ201=.
replace econ201=. if (ec201==-1)
replace econ201=1 if (ec201==100)
replace econ201=1 if (ec201==101)
replace econ201=1 if (ec201==110)
replace econ201=1 if (ec201==111)
replace econ201=1 if (ec201==113)
replace econ201=1 if (ec201==114)
replace econ201=1 if (ec201==120)
replace econ201=1 if (ec201==121)
replace econ201=1 if (ec201==130)
replace econ201=1 if (ec201==131)
replace econ201=1 if (ec201==140)
replace econ201=1 if (ec201==141)
replace econ201=1 if (ec201==150)
replace econ201=1 if (ec201==152)
replace econ201=2 if (ec201==200)
replace econ201=2 if (ec201==201)
replace econ201=2 if (ec201==220)
replace econ201=6 if (ec201==300)
replace econ201=6 if (ec201==400)
replace econ201=3 if (ec201==500)
replace econ201=4 if (ec201==550)
replace econ201=5 if (ec201==600)
replace econ201=5 if (ec201==601)
replace econ201=5 if (ec201==602)
replace econ201=6 if (ec201==700)
replace econ201=6 if (ec201==701)
replace econ201=3 if (ec201==800)

label value econ201 econactivity_lbl

tab econ201

gen econ202=.
replace econ202=. if (ec202==-1)
replace econ202=1 if (ec202==100)
replace econ202=1 if (ec202==101)
replace econ202=1 if (ec202==110)
replace econ202=1 if (ec202==111)
replace econ202=1 if (ec202==113)
replace econ202=1 if (ec202==114)
replace econ202=1 if (ec202==120)
replace econ202=1 if (ec202==121)
replace econ202=1 if (ec202==130)
replace econ202=1 if (ec202==131)
replace econ202=1 if (ec202==140)
replace econ202=1 if (ec202==141)
replace econ202=1 if (ec202==150)
replace econ202=1 if (ec202==152)
replace econ202=2 if (ec202==200)
replace econ202=2 if (ec202==201)
replace econ202=2 if (ec202==220)
replace econ202=6 if (ec202==300)
replace econ202=6 if (ec202==400)
replace econ202=3 if (ec202==500)
replace econ202=4 if (ec202==550)
replace econ202=5 if (ec202==600)
replace econ202=5 if (ec202==601)
replace econ202=5 if (ec202==602)
replace econ202=5 if (ec202==603)
replace econ202=6 if (ec202==700)
replace econ202=6 if (ec202==701)
replace econ202=3 if (ec202==800)

label value econ202 econactivity_lbl

tab econ202

gen econ203=.
replace econ203=. if (ec203==-1)
replace econ203=1 if (ec203==100)
replace econ203=1 if (ec203==101)
replace econ203=1 if (ec203==110)
replace econ203=1 if (ec203==111)
replace econ203=1 if (ec203==113)
replace econ203=1 if (ec203==114)
replace econ203=1 if (ec203==120)
replace econ203=1 if (ec203==121)
replace econ203=1 if (ec203==130)
replace econ203=1 if (ec203==131)
replace econ203=1 if (ec203==140)
replace econ203=1 if (ec203==141)
replace econ203=1 if (ec203==150)
replace econ203=1 if (ec203==152)
replace econ203=2 if (ec203==200)
replace econ203=2 if (ec203==201)
replace econ203=2 if (ec203==220)
replace econ203=6 if (ec203==300)
replace econ203=6 if (ec203==400)
replace econ203=3 if (ec203==500)
replace econ203=4 if (ec203==550)
replace econ203=5 if (ec203==600)
replace econ203=5 if (ec203==601)
replace econ203=5 if (ec203==602)
replace econ203=6 if (ec203==700)
replace econ203=6 if (ec203==701)
replace econ203=3 if (ec203==800)

label value econ203 econactivity_lbl

tab econ203

gen econ204=.
replace econ204=. if (ec204==-1)
replace econ204=1 if (ec204==100)
replace econ204=1 if (ec204==101)
replace econ204=1 if (ec204==110)
replace econ204=1 if (ec204==111)
replace econ204=1 if (ec204==113)
replace econ204=1 if (ec204==114)
replace econ204=1 if (ec204==120)
replace econ204=1 if (ec204==121)
replace econ204=1 if (ec204==130)
replace econ204=1 if (ec204==131)
replace econ204=1 if (ec204==140)
replace econ204=1 if (ec204==141)
replace econ204=1 if (ec204==150)
replace econ204=1 if (ec204==152)
replace econ204=2 if (ec204==200)
replace econ204=2 if (ec204==201)
replace econ204=2 if (ec204==220)
replace econ204=6 if (ec204==300)
replace econ204=6 if (ec204==400)
replace econ204=3 if (ec204==500)
replace econ204=4 if (ec204==550)
replace econ204=5 if (ec204==600)
replace econ204=5 if (ec204==602)
replace econ204=6 if (ec204==700)
replace econ204=6 if (ec204==701)
replace econ204=3 if (ec204==800)

label value econ204 econactivity_lbl

tab econ204

gen econ205=.
replace econ205=. if (ec204==-1)
replace econ205=1 if (ec204==100)
replace econ205=1 if (ec204==101)
replace econ205=1 if (ec204==110)
replace econ205=1 if (ec204==111)
replace econ205=1 if (ec204==113)
replace econ205=1 if (ec204==114)
replace econ205=1 if (ec204==120)
replace econ205=1 if (ec204==121)
replace econ205=1 if (ec204==130)
replace econ205=1 if (ec204==131)
replace econ205=1 if (ec204==140)
replace econ205=1 if (ec204==141)
replace econ205=1 if (ec204==150)
replace econ205=1 if (ec204==152)
replace econ205=2 if (ec204==200)
replace econ205=2 if (ec204==201)
replace econ205=2 if (ec204==220)
replace econ205=6 if (ec204==300)
replace econ205=6 if (ec204==400)
replace econ205=3 if (ec204==500)
replace econ205=4 if (ec204==550)
replace econ205=5 if (ec204==600)
replace econ205=5 if (ec204==602)
replace econ205=6 if (ec204==700)
replace econ205=6 if (ec204==701)
replace econ205=3 if (ec204==800)

label value econ205 econactivity_lbl

tab econ205

.
. gen econ194=.
(18,558 missing values generated)

. replace econ194=. if (ec194==-1)
(0 real changes made)

. replace econ194=1 if (ec194==100)
(222 real changes made)

. replace econ194=1 if (ec194==101)
(1 real change made)

. replace econ194=1 if (ec194==110)
(41 real changes made)

. replace econ194=1 if (ec194==120)
(2 real changes made)

. replace econ194=1 if (ec194==140)
(2 real changes made)

. replace econ194=1 if (ec194==150)
(1 real change made)

. replace econ194=2 if (ec194==200)
(7 real changes made)

. replace econ194=3 if (ec194==500)
(3 real changes made)

. replace econ194=4 if (ec194==550)
(12,110 real changes made)

. replace econ194=5 if (ec194==600)
(17 real changes made)

. replace econ194=6 if (ec194==700)
(71 real changes made)

.
. label define econactivity_lbl 1"Full Time Employment" 2"Part Time Employment"
>  3"Education" 4"School" 5"Unemployment" 6"Out of Labour Force"

. label value econ194 econactivity_lbl

.
. tab econ194

             econ194 |      Freq.     Percent        Cum.
---------------------+-----------------------------------
Full Time Employment |        269        2.16        2.16
Part Time Employment |          7        0.06        2.21
           Education |          3        0.02        2.24
              School |     12,110       97.06       99.29
        Unemployment |         17        0.14       99.43
 Out of Labour Force |         71        0.57      100.00
---------------------+-----------------------------------
               Total |     12,477      100.00

.
. gen econ195=.
(18,558 missing values generated)

. replace econ195=. if (ec195==-1)
(0 real changes made)

. replace econ195=1 if (ec195==100)
(959 real changes made)

. replace econ195=1 if (ec195==101)
(4 real changes made)

. replace econ195=1 if (ec195==110)
(218 real changes made)

. replace econ195=1 if (ec195==120)
(12 real changes made)

. replace econ195=1 if (ec195==140)
(2 real changes made)

. replace econ195=1 if (ec195==150)
(1 real change made)

. replace econ195=1 if (ec195==152)
(1 real change made)

. replace econ195=2 if (ec195==200)
(24 real changes made)

. replace econ195=3 if (ec195==500)
(6 real changes made)

. replace econ195=4 if (ec195==550)
(11,090 real changes made)

. replace econ195=5 if (ec195==600)
(38 real changes made)

. replace econ195=6 if (ec195==700)
(100 real changes made)

.
. label value econ195 econactivity_lbl

.
. tab econ195

             econ195 |      Freq.     Percent        Cum.
---------------------+-----------------------------------
Full Time Employment |      1,197        9.61        9.61
Part Time Employment |         24        0.19        9.80
           Education |          6        0.05        9.85
              School |     11,090       89.04       98.89
        Unemployment |         38        0.31       99.20
 Out of Labour Force |        100        0.80      100.00
---------------------+-----------------------------------
               Total |     12,455      100.00

.
. gen econ196=.
(18,558 missing values generated)

. replace econ196=. if (ec196==-1)
(0 real changes made)

. replace econ196=1 if (ec196==100)
(3,786 real changes made)

. replace econ196=1 if (ec196==101)
(13 real changes made)

. replace econ196=1 if (ec196==110)
(847 real changes made)

. replace econ196=1 if (ec196==111)
(1 real change made)

. replace econ196=1 if (ec196==113)
(5 real changes made)

. replace econ196=1 if (ec196==120)
(76 real changes made)

. replace econ196=1 if (ec196==140)
(6 real changes made)

. replace econ196=1 if (ec196==150)
(2 real changes made)

. replace econ196=1 if (ec196==152)
(1 real change made)

. replace econ196=2 if (ec196==200)
(71 real changes made)

. replace econ196=2 if (ec196==240)
(1 real change made)

. replace econ196=3 if (ec196==500)
(41 real changes made)

. replace econ196=4 if (ec196==550)
(6,685 real changes made)

. replace econ196=5 if (ec196==600)
(195 real changes made)

. replace econ196=5 if (ec196==602)
(1 real change made)

. replace econ196=6 if (ec196==700)
(466 real changes made)

. replace econ196=3 if (ec196==800)
(1 real change made)

.
. label value econ196 econactivity_lbl

.
. tab econ196

             econ196 |      Freq.     Percent        Cum.
---------------------+-----------------------------------
Full Time Employment |      4,737       38.83       38.83
Part Time Employment |         72        0.59       39.42
           Education |         42        0.34       39.77
              School |      6,685       54.80       94.57
        Unemployment |        196        1.61       96.18
 Out of Labour Force |        466        3.82      100.00
---------------------+-----------------------------------
               Total |     12,198      100.00

.
. gen econ197=.
(18,558 missing values generated)

. replace econ197=. if (ec197==-1)
(0 real changes made)

. replace econ197=1 if (ec197==100)
(4,547 real changes made)

. replace econ197=1 if (ec197==101)
(15 real changes made)

. replace econ197=1 if (ec197==110)
(1,281 real changes made)

. replace econ197=1 if (ec197==111)
(3 real changes made)

. replace econ197=1 if (ec197==113)
(8 real changes made)

. replace econ197=1 if (ec197==120)
(94 real changes made)

. replace econ197=1 if (ec197==140)
(13 real changes made)

. replace econ197=1 if (ec197==150)
(2 real changes made)

. replace econ197=1 if (ec197==152)
(1 real change made)

. replace econ197=2 if (ec197==200)
(82 real changes made)

. replace econ197=2 if (ec197==240)
(1 real change made)

. replace econ197=3 if (ec197==500)
(153 real changes made)

. replace econ197=4 if (ec197==550)
(3,893 real changes made)

. replace econ197=5 if (ec197==600)
(493 real changes made)

. replace econ197=5 if (ec197==602)
(13 real changes made)

. replace econ197=6 if (ec197==700)
(1,092 real changes made)

. replace econ197=6 if (ec197==701)
(2 real changes made)

. replace econ197=3 if (ec197==800)
(2 real changes made)

.
. label value econ197 econactivity_lbl

.
. tab econ197

             econ197 |      Freq.     Percent        Cum.
---------------------+-----------------------------------
Full Time Employment |      5,964       51.00       51.00
Part Time Employment |         83        0.71       51.71
           Education |        155        1.33       53.03
              School |      3,893       33.29       86.32
        Unemployment |        506        4.33       90.65
 Out of Labour Force |      1,094        9.35      100.00
---------------------+-----------------------------------
               Total |     11,695      100.00

.
. gen econ198=.
(18,558 missing values generated)

. replace econ198=. if (ec198==-1)
(0 real changes made)

. replace econ198=1 if (ec198==100)
(4,555 real changes made)

. replace econ198=1 if (ec198==101)
(143 real changes made)

. replace econ198=1 if (ec198==110)
(1,767 real changes made)

. replace econ198=1 if (ec198==111)
(16 real changes made)

. replace econ198=1 if (ec198==113)
(23 real changes made)

. replace econ198=1 if (ec198==114)
(1 real change made)

. replace econ198=1 if (ec198==120)
(365 real changes made)

. replace econ198=1 if (ec198==121)
(6 real changes made)

. replace econ198=1 if (ec198==130)
(18 real changes made)

. replace econ198=1 if (ec198==140)
(29 real changes made)

. replace econ198=1 if (ec198==150)
(1 real change made)

. replace econ198=1 if (ec198==152)
(1 real change made)

. replace econ198=2 if (ec198==200)
(70 real changes made)

. replace econ198=2 if (ec198==201)
(2 real changes made)

. replace econ198=2 if (ec198==220)
(3 real changes made)

. replace econ198=6 if (ec198==300)
(1 real change made)

. replace econ198=6 if (ec198==400)
(1 real change made)

. replace econ198=3 if (ec198==500)
(996 real changes made)

. replace econ198=4 if (ec198==550)
(3,833 real changes made)

. replace econ198=5 if (ec198==600)
(334 real changes made)

. replace econ198=5 if (ec198==601)
(2 real changes made)

. replace econ198=5 if (ec198==602)
(19 real changes made)

. replace econ198=6 if (ec198==700)
(212 real changes made)

. replace econ198=6 if (ec198==701)
(2 real changes made)

. replace econ198=3 if (ec198==800)
(10 real changes made)

.
. label value econ198 econactivity_lbl

.
. tab econ198

             econ198 |      Freq.     Percent        Cum.
---------------------+-----------------------------------
Full Time Employment |      6,925       55.80       55.80
Part Time Employment |         75        0.60       56.41
           Education |      1,006        8.11       64.51
              School |      3,833       30.89       95.40
        Unemployment |        355        2.86       98.26
 Out of Labour Force |        216        1.74      100.00
---------------------+-----------------------------------
               Total |     12,410      100.00

.
. gen econ199=.
(18,558 missing values generated)

. replace econ199=. if (ec199==-1)
(0 real changes made)

. replace econ199=1 if (ec199==100)
(4,569 real changes made)

. replace econ199=1 if (ec199==101)
(150 real changes made)

. replace econ199=1 if (ec199==110)
(1,850 real changes made)

. replace econ199=1 if (ec199==111)
(21 real changes made)

. replace econ199=1 if (ec199==113)
(22 real changes made)

. replace econ199=1 if (ec199==114)
(1 real change made)

. replace econ199=1 if (ec199==120)
(383 real changes made)

. replace econ199=1 if (ec199==121)
(6 real changes made)

. replace econ199=1 if (ec199==130)
(18 real changes made)

. replace econ199=1 if (ec199==131)
(1 real change made)

. replace econ199=1 if (ec199==140)
(34 real changes made)

. replace econ199=1 if (ec199==150)
(2 real changes made)

. replace econ199=1 if (ec199==152)
(1 real change made)

. replace econ199=2 if (ec199==200)
(42 real changes made)

. replace econ199=2 if (ec199==201)
(2 real changes made)

. replace econ199=2 if (ec199==220)
(3 real changes made)

. replace econ199=6 if (ec199==300)
(1 real change made)

. replace econ199=6 if (ec199==400)
(1 real change made)

. replace econ199=3 if (ec199==500)
(1,061 real changes made)

. replace econ199=4 if (ec199==550)
(3,796 real changes made)

. replace econ199=5 if (ec199==600)
(286 real changes made)

. replace econ199=5 if (ec199==601)
(2 real changes made)

. replace econ199=5 if (ec199==602)
(14 real changes made)

. replace econ199=6 if (ec199==700)
(159 real changes made)

. replace econ199=6 if (ec199==701)
(3 real changes made)

. replace econ199=3 if (ec199==800)
(11 real changes made)

.
. label value econ199 econactivity_lbl

.
. tab econ199

             econ199 |      Freq.     Percent        Cum.
---------------------+-----------------------------------
Full Time Employment |      7,058       56.74       56.74
Part Time Employment |         47        0.38       57.12
           Education |      1,072        8.62       65.74
              School |      3,796       30.52       96.25
        Unemployment |        302        2.43       98.68
 Out of Labour Force |        164        1.32      100.00
---------------------+-----------------------------------
               Total |     12,439      100.00

.
. gen econ200=.
(18,558 missing values generated)

. replace econ200=. if (ec200==-1)
(0 real changes made)

. replace econ200=1 if (ec200==100)
(4,643 real changes made)

. replace econ200=1 if (ec200==101)
(148 real changes made)

. replace econ200=1 if (ec200==110)
(1,853 real changes made)

. replace econ200=1 if (ec200==111)
(22 real changes made)

. replace econ200=1 if (ec200==113)
(22 real changes made)

. replace econ200=1 if (ec200==114)
(1 real change made)

. replace econ200=1 if (ec200==120)
(386 real changes made)

. replace econ200=1 if (ec200==121)
(4 real changes made)

. replace econ200=1 if (ec200==130)
(18 real changes made)

. replace econ200=1 if (ec200==131)
(1 real change made)

. replace econ200=1 if (ec200==140)
(33 real changes made)

. replace econ200=1 if (ec200==141)
(1 real change made)

. replace econ200=1 if (ec200==150)
(2 real changes made)

. replace econ200=1 if (ec200==152)
(1 real change made)

. replace econ200=2 if (ec200==200)
(39 real changes made)

. replace econ200=2 if (ec200==201)
(2 real changes made)

. replace econ200=2 if (ec200==220)
(3 real changes made)

. replace econ200=6 if (ec200==300)
(1 real change made)

. replace econ200=6 if (ec200==400)
(1 real change made)

. replace econ200=3 if (ec200==500)
(1,055 real changes made)

. replace econ200=4 if (ec200==550)
(3,760 real changes made)

. replace econ200=5 if (ec200==600)
(265 real changes made)

. replace econ200=5 if (ec200==601)
(3 real changes made)

. replace econ200=5 if (ec200==602)
(9 real changes made)

. replace econ200=6 if (ec200==700)
(160 real changes made)

. replace econ200=6 if (ec200==701)
(2 real changes made)

. replace econ200=3 if (ec200==800)
(11 real changes made)

.
. label value econ200 econactivity_lbl

.
. tab econ200

             econ200 |      Freq.     Percent        Cum.
---------------------+-----------------------------------
Full Time Employment |      7,135       57.33       57.33
Part Time Employment |         44        0.35       57.68
           Education |      1,066        8.57       66.25
              School |      3,760       30.21       96.46
        Unemployment |        277        2.23       98.68
 Out of Labour Force |        164        1.32      100.00
---------------------+-----------------------------------
               Total |     12,446      100.00

.
. gen econ201=.
(18,558 missing values generated)

. replace econ201=. if (ec201==-1)
(0 real changes made)

. replace econ201=1 if (ec201==100)
(4,716 real changes made)

. replace econ201=1 if (ec201==101)
(144 real changes made)

. replace econ201=1 if (ec201==110)
(1,842 real changes made)

. replace econ201=1 if (ec201==111)
(22 real changes made)

. replace econ201=1 if (ec201==113)
(21 real changes made)

. replace econ201=1 if (ec201==114)
(1 real change made)

. replace econ201=1 if (ec201==120)
(366 real changes made)

. replace econ201=1 if (ec201==121)
(4 real changes made)

. replace econ201=1 if (ec201==130)
(20 real changes made)

. replace econ201=1 if (ec201==131)
(1 real change made)

. replace econ201=1 if (ec201==140)
(35 real changes made)

. replace econ201=1 if (ec201==141)
(1 real change made)

. replace econ201=1 if (ec201==150)
(2 real changes made)

. replace econ201=1 if (ec201==152)
(1 real change made)

. replace econ201=2 if (ec201==200)
(37 real changes made)

. replace econ201=2 if (ec201==201)
(2 real changes made)

. replace econ201=2 if (ec201==220)
(2 real changes made)

. replace econ201=6 if (ec201==300)
(1 real change made)

. replace econ201=6 if (ec201==400)
(1 real change made)

. replace econ201=3 if (ec201==500)
(1,046 real changes made)

. replace econ201=4 if (ec201==550)
(3,717 real changes made)

. replace econ201=5 if (ec201==600)
(276 real changes made)

. replace econ201=5 if (ec201==601)
(3 real changes made)

. replace econ201=5 if (ec201==602)
(11 real changes made)

. replace econ201=6 if (ec201==700)
(164 real changes made)

. replace econ201=6 if (ec201==701)
(3 real changes made)

. replace econ201=3 if (ec201==800)
(11 real changes made)

.
. label value econ201 econactivity_lbl

.
. tab econ201

             econ201 |      Freq.     Percent        Cum.
---------------------+-----------------------------------
Full Time Employment |      7,176       57.64       57.64
Part Time Employment |         41        0.33       57.97
           Education |      1,057        8.49       66.46
              School |      3,717       29.86       96.31
        Unemployment |        290        2.33       98.64
 Out of Labour Force |        169        1.36      100.00
---------------------+-----------------------------------
               Total |     12,450      100.00

.
. gen econ202=.
(18,558 missing values generated)

. replace econ202=. if (ec202==-1)
(0 real changes made)

. replace econ202=1 if (ec202==100)
(4,719 real changes made)

. replace econ202=1 if (ec202==101)
(149 real changes made)

. replace econ202=1 if (ec202==110)
(1,855 real changes made)

. replace econ202=1 if (ec202==111)
(23 real changes made)

. replace econ202=1 if (ec202==113)
(22 real changes made)

. replace econ202=1 if (ec202==114)
(2 real changes made)

. replace econ202=1 if (ec202==120)
(384 real changes made)

. replace econ202=1 if (ec202==121)
(4 real changes made)

. replace econ202=1 if (ec202==130)
(20 real changes made)

. replace econ202=1 if (ec202==131)
(1 real change made)

. replace econ202=1 if (ec202==140)
(37 real changes made)

. replace econ202=1 if (ec202==141)
(1 real change made)

. replace econ202=1 if (ec202==150)
(4 real changes made)

. replace econ202=1 if (ec202==152)
(2 real changes made)

. replace econ202=2 if (ec202==200)
(38 real changes made)

. replace econ202=2 if (ec202==201)
(3 real changes made)

. replace econ202=2 if (ec202==220)
(2 real changes made)

. replace econ202=6 if (ec202==300)
(1 real change made)

. replace econ202=6 if (ec202==400)
(1 real change made)

. replace econ202=3 if (ec202==500)
(1,042 real changes made)

. replace econ202=4 if (ec202==550)
(3,655 real changes made)

. replace econ202=5 if (ec202==600)
(295 real changes made)

. replace econ202=5 if (ec202==601)
(3 real changes made)

. replace econ202=5 if (ec202==602)
(6 real changes made)

. replace econ202=5 if (ec202==603)
(1 real change made)

. replace econ202=6 if (ec202==700)
(168 real changes made)

. replace econ202=6 if (ec202==701)
(3 real changes made)

. replace econ202=3 if (ec202==800)
(12 real changes made)

.
. label value econ202 econactivity_lbl

.
. tab econ202

             econ202 |      Freq.     Percent        Cum.
---------------------+-----------------------------------
Full Time Employment |      7,223       58.00       58.00
Part Time Employment |         43        0.35       58.35
           Education |      1,054        8.46       66.81
              School |      3,655       29.35       96.16
        Unemployment |        305        2.45       98.61
 Out of Labour Force |        173        1.39      100.00
---------------------+-----------------------------------
               Total |     12,453      100.00

.
. gen econ203=.
(18,558 missing values generated)

. replace econ203=. if (ec203==-1)
(0 real changes made)

. replace econ203=1 if (ec203==100)
(4,770 real changes made)

. replace econ203=1 if (ec203==101)
(151 real changes made)

. replace econ203=1 if (ec203==110)
(1,851 real changes made)

. replace econ203=1 if (ec203==111)
(24 real changes made)

. replace econ203=1 if (ec203==113)
(18 real changes made)

. replace econ203=1 if (ec203==114)
(2 real changes made)

. replace econ203=1 if (ec203==120)
(371 real changes made)

. replace econ203=1 if (ec203==121)
(4 real changes made)

. replace econ203=1 if (ec203==130)
(20 real changes made)

. replace econ203=1 if (ec203==131)
(1 real change made)

. replace econ203=1 if (ec203==140)
(37 real changes made)

. replace econ203=1 if (ec203==141)
(1 real change made)

. replace econ203=1 if (ec203==150)
(4 real changes made)

. replace econ203=1 if (ec203==152)
(2 real changes made)

. replace econ203=2 if (ec203==200)
(37 real changes made)

. replace econ203=2 if (ec203==201)
(2 real changes made)

. replace econ203=2 if (ec203==220)
(2 real changes made)

. replace econ203=6 if (ec203==300)
(1 real change made)

. replace econ203=6 if (ec203==400)
(1 real change made)

. replace econ203=3 if (ec203==500)
(1,026 real changes made)

. replace econ203=4 if (ec203==550)
(3,631 real changes made)

. replace econ203=5 if (ec203==600)
(308 real changes made)

. replace econ203=5 if (ec203==601)
(2 real changes made)

. replace econ203=5 if (ec203==602)
(9 real changes made)

. replace econ203=6 if (ec203==700)
(168 real changes made)

. replace econ203=6 if (ec203==701)
(3 real changes made)

. replace econ203=3 if (ec203==800)
(12 real changes made)

.

Some interesting findings. It appears that once exams are over with (1974m6) we see that around 30% of individuals stay in school, with around 55% going straight into work and around 8% going on to higher education. Unemployment remains steady at around 2%.

I am intending to look at the number of o-levels passed within this cohort. To do this I have located two varaibles that will need to be recoded in order for this to be possible. The varaible n4656 measures the number of o-level passes and the variable n4655 measures whether an individual passed a single o-level or not. The two variables will need to be recoded into a singular variable for the purpose of including 0s into the analysis. Leaving out 0s would present issues with analysis. The summary of these dependent variables is below:

In [5]:
%%stata

gen opass=.
replace opass=0 if (n4655==2)
replace opass=1 if (n4656==1)
replace opass=2 if (n4656==2)
replace opass=3 if (n4656==3)
replace opass=4 if (n4656==4)
replace opass=5 if (n4656==5)
replace opass=6 if (n4656==6)
replace opass=7 if (n4656==7)
replace opass=8 if (n4656==8)
replace opass=9 if (n4656==9)

label define opass_lbl 0"0" 1"1" 2"2" 3"3" 4"4" 5"5" 6"6" 7"7" 8"8" 9"9 or More"
label value opass opass_lbl

.
. gen opass=.
(18,558 missing values generated)

. replace opass=0 if (n4655==2)
(4,880 real changes made)

. replace opass=1 if (n4656==1)
(1,224 real changes made)

. replace opass=2 if (n4656==2)
(823 real changes made)

. replace opass=3 if (n4656==3)
(670 real changes made)

. replace opass=4 if (n4656==4)
(680 real changes made)

. replace opass=5 if (n4656==5)
(830 real changes made)

. replace opass=6 if (n4656==6)
(719 real changes made)

. replace opass=7 if (n4656==7)
(772 real changes made)

. replace opass=8 if (n4656==8)
(719 real changes made)

. replace opass=9 if (n4656==9)
(1,193 real changes made)

.
. label define opass_lbl 0"0" 1"1" 2"2" 3"3" 4"4" 5"5" 6"6" 7"7" 8"8" 9"9 or Mo
> re"

. label value opass opass_lbl

.

Reflecting on the summary statistics of this newly created dependent variable:

In [6]:
%%stata

tab opass
summarize opass

.
. tab opass

      opass |      Freq.     Percent        Cum.
------------+-----------------------------------
          0 |      4,880       39.01       39.01
          1 |      1,224        9.78       48.79
          2 |        823        6.58       55.37
          3 |        670        5.36       60.73
          4 |        680        5.44       66.16
          5 |        830        6.63       72.80
          6 |        719        5.75       78.55
          7 |        772        6.17       84.72
          8 |        719        5.75       90.46
  9 or More |      1,193        9.54      100.00
------------+-----------------------------------
      Total |     12,510      100.00

. summarize opass

    Variable |        Obs        Mean    Std. dev.       Min        Max
-------------+---------------------------------------------------------
       opass |     12,510    3.034133    3.265265          0          9

.

In [7]:
%%stata

histogram opass, frequency ytitle(Frequency of Individuals) xtitle(Number of O-Level Passes) title(Distribution of O-Level Passes) scheme(meta)

.
. histogram opass, frequency ytitle(Frequency of Individuals) xtitle(Number of
> O-Level Passes) title(Distribution of O-Level Passes) scheme(meta)
(bin=40, start=0, width=.225)

.

From previous literature it is fair to suggest that those that attain a decent amount of O-level passes would continue on with their education.

In [8]:
%%stata

gen educur=.
replace educur=0 if (curred==0)
replace educur=1 if (curred==1)
replace educur=1 if (curred==2)
replace educur=0 if (curred==3)


label define educur_lbl 0"Not In Education" 1"In Education"
label value educur educur_lbl

tab educur

.
. gen educur=.
(18,558 missing values generated)

. replace educur=0 if (curred==0)
(11,750 real changes made)

. replace educur=1 if (curred==1)
(300 real changes made)

. replace educur=1 if (curred==2)
(467 real changes made)

. replace educur=0 if (curred==3)
(19 real changes made)

.
.
. label define educur_lbl 0"Not In Education" 1"In Education"

. label value educur educur_lbl

.
. tab educur

          educur |      Freq.     Percent        Cum.
-----------------+-----------------------------------
Not In Education |     11,769       93.88       93.88
    In Education |        767        6.12      100.00
-----------------+-----------------------------------
           Total |     12,536      100.00

.

Now to reflect on the idea that individuals with high levels of educational attainment tend to remain in education.

In [9]:
%%stata

tab2 opass educur

.
. tab2 opass educur

-> tabulation of opass by educur

           |        educur
     opass | Not In Ed  In Educat |     Total
-----------+----------------------+----------
         0 |     4,818         62 |     4,880
         1 |     1,182         42 |     1,224
         2 |       798         25 |       823
         3 |       638         32 |       670
         4 |       645         35 |       680
         5 |       755         75 |       830
         6 |       663         56 |       719
         7 |       685         87 |       772
         8 |       588        131 |       719
 9 or More |       972        221 |     1,193
-----------+----------------------+----------
     Total |    11,744        766 |    12,510

.

As seen here, individauls with high levels of educational attainment seem to remain in education at higher rates. To explore this further I will first transform my O-level pass variable into a dichotomas <5 O-level passes or 5 or more O-Level passes. Then run a simple logistic regression model.

In [10]:
%%stata

gen obin=.
replace obin=0 if (opass==0)
replace obin=0 if (opass==1)
replace obin=0 if (opass==2)
replace obin=0 if (opass==3)
replace obin=0 if (opass==4)
replace obin=1 if (opass==5)
replace obin=1 if (opass==6)
replace obin=1 if (opass==7)
replace obin=1 if (opass==8)
replace obin=1 if (opass==9)

label define obin_lbl 0"<5 O-Level Passes" 1"5 or More O-Level Passes" 
label value obin obin_lbl

tab obin

tab2 obin educur

logit obin i.educur, or

.
. gen obin=.
(18,558 missing values generated)

. replace obin=0 if (opass==0)
(4,880 real changes made)

. replace obin=0 if (opass==1)
(1,224 real changes made)

. replace obin=0 if (opass==2)
(823 real changes made)

. replace obin=0 if (opass==3)
(670 real changes made)

. replace obin=0 if (opass==4)
(680 real changes made)

. replace obin=1 if (opass==5)
(830 real changes made)

. replace obin=1 if (opass==6)
(719 real changes made)

. replace obin=1 if (opass==7)
(772 real changes made)

. replace obin=1 if (opass==8)
(719 real changes made)

. replace obin=1 if (opass==9)
(1,193 real changes made)

.
. label define obin_lbl 0"<5 O-Level Passes" 1"5 or More O-Level Passes"

. label value obin obin_lbl

.
. tab obin

                    obin |      Freq.     Percent        Cum.
-------------------------+-----------------------------------
       <5 O-Level Passes |      8,277       66.16       66.16
5 or More O-Level Passes |      4,233       33.84      100.00
-------------------------+-----------------------------------
                   Total |     12,510      100.00

.
. tab2 obin educur

-> tabulation of obin by educur

                      |        educur
                 obin | Not In Ed  In Educat |     Total
----------------------+----------------------+----------
    <5 O-Level Passes |     8,081        196 |     8,277
5 or More O-Level Pas |     3,663        570 |     4,233
----------------------+----------------------+----------
                Total |    11,744        766 |    12,510

.
. logit obin i.educur, or

Iteration 0:   log likelihood = -8005.7484
Iteration 1:   log likelihood = -7724.5373
Iteration 2:   log likelihood =  -7724.132
Iteration 3:   log likelihood = -7724.1318

Logistic regression                                     Number of obs = 12,510
                                                        LR chi2(1)    = 563.23
                                                        Prob > chi2   = 0.0000
Log likelihood = -7724.1318                             Pseudo R2     = 0.0352

------------------------------------------------------------------------------
        obin | Odds ratio   Std. err.      z    P>|z|     [95% conf. interval]
-------------+----------------------------------------------------------------
      educur |
In Educat..  |    6.41574   .5464001    21.83   0.000     5.429423    7.581232
       _cons |   .4532855   .0090288   -39.72   0.000     .4359304    .4713315
------------------------------------------------------------------------------
Note: _cons estimates baseline odds.

.

In [11]:
%%stata

outreg2 using logistic.doc, replace ctitle(Model 1)

.
. outreg2 using logistic.doc, replace ctitle(Model 1)
file using "logistic.doc" is read-only; cannot be modified or erased
The file needs to be closed if being used by another software such as Word.

Exception in thread Stata:
Traceback (most recent call last):
  File "C:\Users\scott\anaconda3\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "E:\Stata SE\utilities\pystata\core\stout.py", line 176, in run
    raise SystemError(output)
SystemError: r(608);
r(608);

This logistic regression model depicts that individuals who are in Education has a 6.4 times the odds of those that are not in Education of obtaining 5 or more O-level passes.

In [12]:
%%stata

coefplot, vertical drop(_cons) 

margins i.educur

margins r.educur

.
. coefplot, vertical drop(_cons)

.
. margins i.educur

Adjusted predictions                                    Number of obs = 12,510
Model VCE: OIM

Expression: Pr(obin), predict()

------------------------------------------------------------------------------
             |            Delta-method
             |     Margin   std. err.      z    P>|z|     [95% conf. interval]
-------------+----------------------------------------------------------------
      educur |
Not In Ed..  |    .311904   .0042749    72.96   0.000     .3035253    .3202826
In Educat..  |   .7441252    .015766    47.20   0.000     .7132244    .7750261
------------------------------------------------------------------------------

.
. margins r.educur

Contrasts of adjusted predictions                       Number of obs = 12,510
Model VCE: OIM

Expression: Pr(obin), predict()

------------------------------------------------
             |         df        chi2     P>chi2
-------------+----------------------------------
      educur |          1      700.10     0.0000
------------------------------------------------

--------------------------------------------------------------------
                   |            Delta-method
                   |   Contrast   std. err.     [95% conf. interval]
-------------------+------------------------------------------------
            educur |
    (In Education  |
               vs  |
Not In Education)  |   .4322213   .0163353      .4002046    .4642379
--------------------------------------------------------------------

.

On average, 74 out of 100 people in education obtain 5 or more O-Level passes, while only 3 out of 100 do so who are not in education (predictive margins). Accordingly, being In education increases a person's likelihood of having obtained 5 or more O-Levels by 43 percentage points. Now onto the more complex models that include covariates such as sex, ethnicity, fathers social class:

In [13]:
%%stata

gen sex=.
replace sex=0 if (n5260==1)
replace sex=1 if (n5260==2)

label define sex_lbl 0"Female" 1"Male"
label value sex sex_lbl

gen ethnic=.
replace ethnic=0 if (n2017==1)
replace ethnic=1 if (n2017==2)
replace ethnic=1 if (n2017==3)
replace ethnic=1 if (n2017==4)
replace ethnic=1 if (n2017==5)
replace ethnic=1 if (n2017==6)

label define ethnic_lbl 0"White" 1"Non-White"
label value ethnic ethnic_lbl

gen fclass=.
replace fclass=1 if (n2384==1)
replace fclass=2 if (n2384==2)
replace fclass=3 if (n2384==3)
replace fclass=4 if (n2384==4)
replace fclass=5 if (n2384==5)
replace fclass=6 if (n2384==6)
replace fclass=7 if (n2384==7)

label define class_lbl 1"Professional" 2"Inter-mediate prof" 3"Skilled non-manual" 4"Skilled manual" 5"Semi-skilled Non-manual" 6"Semi-skilled manual" 7"Unskilled Manual"
label value fclass class_lbl

.
. gen sex=.
(18,558 missing values generated)

. replace sex=0 if (n5260==1)
(6,270 real changes made)

. replace sex=1 if (n5260==2)
(6,266 real changes made)

.
. label define sex_lbl 0"Female" 1"Male"

. label value sex sex_lbl

.
. gen ethnic=.
(18,558 missing values generated)

. replace ethnic=0 if (n2017==1)
(10,953 real changes made)

. replace ethnic=1 if (n2017==2)
(163 real changes made)

. replace ethnic=1 if (n2017==3)
(156 real changes made)

. replace ethnic=1 if (n2017==4)
(24 real changes made)

. replace ethnic=1 if (n2017==5)
(51 real changes made)

. replace ethnic=1 if (n2017==6)
(71 real changes made)

.
. label define ethnic_lbl 0"White" 1"Non-White"

. label value ethnic ethnic_lbl

.
. gen fclass=.
(18,558 missing values generated)

. replace fclass=1 if (n2384==1)
(569 real changes made)

. replace fclass=2 if (n2384==2)
(2,100 real changes made)

. replace fclass=3 if (n2384==3)
(1,004 real changes made)

. replace fclass=4 if (n2384==4)
(4,661 real changes made)

. replace fclass=5 if (n2384==5)
(155 real changes made)

. replace fclass=6 if (n2384==6)
(1,403 real changes made)

. replace fclass=7 if (n2384==7)
(608 real changes made)

.
. label define class_lbl 1"Professional" 2"Inter-mediate prof" 3"Skilled non-ma
> nual" 4"Skilled manual" 5"Semi-skilled Non-manual" 6"Semi-skilled manual" 7"U
> nskilled Manual"

. label value fclass class_lbl

.

In [14]:
%%stata

tab2 educur sex
tab2 educur ethnic
tab2 educur fclass

.
. tab2 educur sex

-> tabulation of educur by sex

                 |          sex
          educur |    Female       Male |     Total
-----------------+----------------------+----------
Not In Education |     5,978      5,791 |    11,769
    In Education |       292        475 |       767
-----------------+----------------------+----------
           Total |     6,270      6,266 |    12,536

. tab2 educur ethnic

-> tabulation of educur by ethnic

                 |        ethnic
          educur |     White  Non-White |     Total
-----------------+----------------------+----------
Not In Education |     8,322        233 |     8,555
    In Education |       562         29 |       591
-----------------+----------------------+----------
           Total |     8,884        262 |     9,146

. tab2 educur fclass

-> tabulation of educur by fclass

                 |                   fclass
          educur | Professio  Inter-med  Skilled n  Skilled m |     Total
-----------------+--------------------------------------------+----------
Not In Education |       397      1,582        779      3,634 |     8,018
    In Education |        82        172         56        169 |       536
-----------------+--------------------------------------------+----------
           Total |       479      1,754        835      3,803 |     8,554


                 |              fclass
          educur | Semi-skil  Semi-skil  Unskilled |     Total
-----------------+---------------------------------+----------
Not In Education |       121      1,076        429 |     8,018
    In Education |         4         41         12 |       536
-----------------+---------------------------------+----------
           Total |       125      1,117        441 |     8,554

.

In [15]:
%%stata

logit obin i.educur i.sex i.ethnic i.fclass, or

.
. logit obin i.educur i.sex i.ethnic i.fclass, or

Iteration 0:   log likelihood = -4840.5515
Iteration 1:   log likelihood = -4247.9923
Iteration 2:   log likelihood = -4243.7529
Iteration 3:   log likelihood = -4243.7511
Iteration 4:   log likelihood = -4243.7511

Logistic regression                                    Number of obs =   7,379
                                                       LR chi2(9)    = 1193.60
                                                       Prob > chi2   =  0.0000
Log likelihood = -4243.7511                            Pseudo R2     =  0.1233

------------------------------------------------------------------------------
        obin | Odds ratio   Std. err.      z    P>|z|     [95% conf. interval]
-------------+----------------------------------------------------------------
      educur |
In Educat..  |   5.318453   .6266191    14.18   0.000     4.221793    6.699984
             |
         sex |
       Male  |   .7943113   .0420866    -4.35   0.000     .7159617    .8812349
             |
      ethnic |
  Non-White  |   .9256738   .1674131    -0.43   0.669     .6494019    1.319479
             |
      fclass |
Inter-med..  |   .3788253   .0493534    -7.45   0.000     .2934569    .4890279
Skilled n..  |   .2176423   .0309084   -10.74   0.000     .1647632    .2874923
Skilled m..  |   .1082942   .0136433   -17.64   0.000     .0845995    .1386254
Semi-skil..  |   .0863956   .0223862    -9.45   0.000     .0519918    .1435651
Semi-skil..  |   .0762596   .0110231   -17.80   0.000     .0574455    .1012356
Unskilled..  |    .054427   .0104082   -15.22   0.000     .0374142    .0791757
             |
       _cons |    3.48123   .4271775    10.17   0.000     2.737051    4.427745
------------------------------------------------------------------------------
Note: _cons estimates baseline odds.

.

In [16]:
%%stata

outreg2 using logistic.doc, replace ctitle(Model 2)

.
. outreg2 using logistic.doc, replace ctitle(Model 2)
file using "logistic.doc" is read-only; cannot be modified or erased
The file needs to be closed if being used by another software such as Word.

Exception in thread Stata:
Traceback (most recent call last):
  File "C:\Users\scott\anaconda3\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "E:\Stata SE\utilities\pystata\core\stout.py", line 176, in run
    raise SystemError(output)
SystemError: r(608);
r(608);

This logistic regression model depicts that individuals who are in Education has a 5.3 times the odds of those that are not in Education of obtaining 5 or more O-level passes when controlling for all other covariates, Those that are Men are 0.8 times the odds compared to women of obtaining 5 or more O-level passes, ethnic minorities are not statistically signficicant. Interestingly there is a very apparent trend looking at fathers social class. There is a significant downward trend when comparing professional social class to others that shows those on the lower end of the social class hierarchy have worse odds in comparison to the sons of professionals in obtaining 5 or more O-level passes.

In [17]:
%%stata

coefplot, vertical drop(_cons) keep(*.fclass)

.
. coefplot, vertical drop(_cons) keep(*.fclass)

.

All she wrote for the NCDS thus far. Now lets begin to compare and contrast with the other databases, first the BCS.

In [18]:
%%stata

save"C:\Users\scott\Desktop\Stata data and do\NCDS\master9.dta"
use"C:\Users\scott\Desktop\Stata data and do\BCS\BCS Sweep 16\stata\stata11_se\bcs7016x.dta"
drop flag_c flag_e flag_f flag_g flag_h flag_j flag_l flag_o flag_p flag_q flag_r flag_t fdoc_mt fdoc_yr gdoc_mt gdoc_yr hdoc_mt hdoc_yr ldoc_mt ldoc_yr odoc_mt odoc_yr pdoc_mt pdoc_yr qdoc_mt qdoc_yr rdoc_mt rdoc_yr tdoc_mt tdoc_yr bversion cvo1 cvo2 cvo3 cvo4 cvo5 cvo6 cvo7 cvo8 cvo9 cvo10 cvo11 cvo12 cvo13 cvo14 cvo15 cvo16 cvo17 cvo18 cvo19 cvo20 cvo21 cvo22 cvo23 cvo24 cvo25 cvo26 cvo27 cvo28 cvo29 cvo30 cvo31 cvo32 cvo33 cvo34 cvo35 cvo36 cvo37 cvo38 cvo39 cvo40 cvo41 cvo42 cvo43 cvo44 cvo45 cvo46 cvo47 cvo48 cvo49 cvo50 cvo51 cvo52 cvo53 cvo54 cvo55 cvo56 cvo57 cvo58 cvo59 cvo60 cvo61 cvo62 cvo63 cvo64 cvo65 cvo66 cvo67 cvo68 cvo69 cvo70 cvo71 cvo72 cvo73 cvo74 cvo75 c5a1 c5a2 c5a3 c5a4 c5a5 c5a6 c5a7 c5a8 c5a9 c5b1 c5b2 c5b3 c5b4 c5b5 c5b6 c5b7 c5b8 c5b9 c5b10 c5c1 c5c2 c5c3 c5c4 c5c5 c5c6 c5c7 c5c8 c5c9 c5c10 c5c11 c5c12 c5c13 c5c14 c5c15 c5c16 c5c17 c5d1 c5d2 c5d3 c5d4 c5d5 c5d6 c5d7 c5d8 c5d9 c5d10 c5d11 c5d12 c5d13 c5d14 c5d15 c5d16 c5e1 c5e2 c5e3 c5e4 c5e5 c5e6 c5e7 c5e8 c5e9 c5e10 c5e11 c5e12 c5e13 c5e14 c5e15 c5f1 c5f2 c5f3 c5f4 c5f5 c5f6 c5f7 c5f8 c5f9 c5f10 c5f11 c5f12 c5f13 c5f14 c5f15 c5f16 c5f17 c5g1 c5g2 c5g3 c5g4 c5g5 c5g6 c5g7 c5g8 c5g9 c5g10 c5g11 c5g12 c5g13 c5g14 c5g15 c5g16 c5g17 c5g18 c5g19 c5g20 c5g21 c5g22 c5g23 c5g24 c5g25 c5g26 c5g27 c5g28 c5h1 c5h2 c5h3 c5h4 c5h5 c5h6 c5h7 c5h8 c5h9 c5h10 c5h11 c5h12 c5h13 c5h14 c5h15 c5h16 c5h17 c5h18 c5h19 c5h20 c5h21 c5h22 c5h23 c5h24 c5h25 c5h26 c5h27 c5i1 c5i2 c5i3 c5i4 c5i5 c5i6 c5i7 c5i8 c5i9 c5i10 c5i11 c5i12 c5j1a c5j2a c5j3a c5j4a c5j5a c5j6a c5j7a c5j8a c5j9a c5j10a c5j11a c5j12a c5j13a c5j14a c5j15a c5j16a c5j17a c5j18a c5j19a c5j20a c5j21a c5j22a c5j23a c5j24a c5j25a c5j26a c5j27a c5j28a c5j29a c5j30a c5j31a c5j32a c5j33a c5j34a c5j35a c5j36a c5j37a c5j38a c5j39a c5j40a c5j41a c5j42a c5j43a c5j44a c5j45a c5j46a c5j47a c5j1b c5j2b c5j3b c5j4b c5j5b c5j6b c5j7b c5j8b c5j9b c5j10b c5j11b c5j12b c5j13b c5j14b c5j15b c5j16b c5j17b c5j18b c5j19b c5j20b c5j21b c5j22b c5j23b c5j24b c5j25b c5j26b c5j27b c5j28b c5j29b c5j30b c5j31b c5j32b c5j33b c5j34b c5j35b c5j36b c5j37b c5j38b c5j39b c5j40b c5j41b c5j42b c5j43b c5j44b c5j45b c5j46b c5j47b c5k1 c5k2 c5k3 c5k4 c5k5 c5k6 c5k7 c5k8 c5k9 c5k10 c5k11  c5k12 c5k13 c5k14 c5k15 c5k16 c5k17 c5k18 c5k19 c5k20 c5k21 c5k22 c5k23 c5k24 c5k25 c5k26 c5k27 c5k28 c5k29 c5k30 c5k31 c5k32 c5k33 c5k34 c5k35 c5k36 c5k37 c5k38 c5k39 c5k40 c5k41 c5k42 c5k43 c5k44 c5k45 c5k46 c5k47 c5k48 c5k49 c5l1 c5l2 c5l3 c5l4 c5l5 c5l6 c5l7 c5l8 c5l9 c5l10 c5l11 c5l12 c5l13 c5l14 c5l15 c5l16 c5l17 c5l18 c5l19 c5l20 c5l21 c5l22 c5l23 c5l24 c5l25 c5l26 c5m1 c5m2 c5m3 c5m4 c5m5 c5m6 c5m7 c5m8 c5m9 c5m10 c5m11 c5m12 c5m13 c5m14 c5m15 c5m16 c5m17 c5m18 c5m19 c5m20 c5m21 c5m22 c5m23 c5m24 c5m25 c5n1 c5n2 c5n3 c5n4 c5n5 c5n6 c5n7 c5n8 c5n9 c5n10 c5n11 c5n12 c5n13 c5n14 c5n15 c5n16 c5n17 c5n18 c5n19 c5n20 c5n21 c5n22 c5o1 c5o2 c5o3 c5o4 c5o5 c5o6 c5o7 c5o8 c5o9 c5o10 c5o11 c5o12 c5o13 c5o14 c5o15 c5o16 c5o17 c5o18 c5o19 c5o20 c5o21 c5o22 c5p1 c5p2 c5p3 c5p4 c5p5 c5p6 c5p7 c5p8 c5p9 c5p10 c5p11 c5p12 c5p13 c5p14 c5p15 c5p16 c5p17 c5p18 c5p19 c5p20 c5p21 c5q1 c5q2 c5q3 c5q4 c5q5 c5q6 c5q7 c5q8 c5q9 c5q10 c5q11 c5q12 c5q13 c5q14 c5q15 c5q16 c5q17 c5q18 c5q19 c5q20 c5q21 c5q22 c5q23 c5q24 c5q25 c5q26 c5q27 c5q28 c5q29 c5q30 c5r1 c5r2 c5r3 c5r4 c5r5 c5r6 c5r7 c5r8 c5r9 c5r10 c5r11 c5r12 c5r13 c5r14 c5r15 c5s1 c5s2 c5s3 c5s4 c5s5 c5s6 c5s7 c5s8 c5s9 c5s10 c5t1 c5t2 c5t3 c5t4 c5t5 c5t6 c5t7 c5t8 c5t9 c5t10 c5t11 c5t12 c5t13 c5t14 c5t15 c5t16 c5t17 c5t18 c5t19 c5t20 c5t21 c5t22 c5t23 c5u1 c5u2 c5u3 c5u4 c5u5 c5u6 c5u7 c5u8 c5u9 c5u10 c5u11 c5u12 c5u13 c5u14 c5u15 c5u16 c5u17 c5u18 c6_2 c6_3a c6_3b c6_4a c6_4b c6_5 c6_6a c6_6b c6_6c c6_7 c6_8 c6_9 c6_10 c6_11 c6_12 c6_13 c6_14 c6_15 c6_16 c6_17 c6_18 c6_19 c7a1 c7a2 c7a3 c7a4 c7a5 c7a6 c7a7 c7a8 c7a9 c7a10 c7a11 c7a12 c7a13 c7a14 c7a15 c7a16 c7a17 c7a18 c7a19 c7a20 c7a21 c7a22 c7a23 c7a24 c7a25 c7a26 c7a27 c7a28 c7a29 c7a30 c7a31 c7a32 c7a33 c7a34 c7a35 c7a36 c7a37 c7a38 c7a39 c7a40 c7a41 c7a42 c7a43 c7a44 c7a45 c7a46 c7a47 c7a48 c7a49 c7a50 c7a51 c7a52 c7a53 c7a54 c7a55 c7a56 c7a57 c7a58 c7a59 c7a60 c7a61 c7a62 c7a63 c7a64 c7a65 c7a66 c7a67 c7a68 c7a69 c7a70 c7a71 c7a72 c7a73 c7a74 c7a75 c7a76 c7a77 c7a78 c7a79 c7a80 c7a81 c7a82 c7a83 c7a84 c7a85 c7a86 c7a87 c7a88 c7a89 c7a90 c7a91 c7a92 c7a93 c7a94 c7a95 c7a96 c7a97 c7a98 c7a99 c7a100 c7b1 c7b2 c7b3 c7b4 c7b5 c7b6 c7b7 c7b8 c7b9 c7b10 c7b11 c7b12 c7b13 c7b14 c7b15 c7b16 c7b17 c7b18 c7b19 c7b20 c7b21 c7b22 c7b23 c7b24 c7b25 c7b26 c7b27 c7b28 c7b29 c7b30 c7b31 c7b32 c7b33 c7b34 c7b35 c7b36 c7b37 c7b38 c7b39 c7b40 c7b41 c7b42 c7b43 c7b44 c7b45 c7b46 c7b47 c7b48 c7b49 c7b50 c7b51 c7b52 c7b53 c7b54 c7b55 c7b56 c7b57 c7b58 c7b59 c7b60 c7b61 c7b62 c7b63 c7b64 c7b65 c7b66 c7b67 c7b68 c7b69 c7b70 c7b71 c7b72 c7b73 c7b74 c7b75 c7b76 c7b77 c7b78 c7b79 c7b80 c7b81 c7b82 c7b83 c7b84 c7b85 c7b86 c7b87 c7b88 c7b89 c7b90 c7b91 c7b92 c7b93 c7b94 c7b95 c7b96 c7b97 c7b98 c7b99 c7b100 e1 e2 e3 e4 e5 e6 e7 e8 e9 e10 e11 e12 e13 e14 e15 e16

cd"C:\Users\scott\Desktop\Stata data and do\BCS\BCS Sweep 26\stata\stata11"

merge 1:1 bcsid using bcs96x.dta
drop _merge

.
. save"C:\Users\scott\Desktop\Stata data and do\NCDS\master8.dta"
file C:\Users\scott\Desktop\Stata data and do\NCDS\master8.dta saved

. use"C:\Users\scott\Desktop\Stata data and do\BCS\BCS Sweep 16\stata\stata11_s
> e\bcs7016x.dta"

. drop flag_c flag_e flag_f flag_g flag_h flag_j flag_l flag_o flag_p flag_q fl
> ag_r flag_t fdoc_mt fdoc_yr gdoc_mt gdoc_yr hdoc_mt hdoc_yr ldoc_mt ldoc_yr o
> doc_mt odoc_yr pdoc_mt pdoc_yr qdoc_mt qdoc_yr rdoc_mt rdoc_yr tdoc_mt tdoc_y
> r bversion cvo1 cvo2 cvo3 cvo4 cvo5 cvo6 cvo7 cvo8 cvo9 cvo10 cvo11 cvo12 cvo
> 13 cvo14 cvo15 cvo16 cvo17 cvo18 cvo19 cvo20 cvo21 cvo22 cvo23 cvo24 cvo25 cv
> o26 cvo27 cvo28 cvo29 cvo30 cvo31 cvo32 cvo33 cvo34 cvo35 cvo36 cvo37 cvo38 c
> vo39 cvo40 cvo41 cvo42 cvo43 cvo44 cvo45 cvo46 cvo47 cvo48 cvo49 cvo50 cvo51
> cvo52 cvo53 cvo54 cvo55 cvo56 cvo57 cvo58 cvo59 cvo60 cvo61 cvo62 cvo63 cvo64
>  cvo65 cvo66 cvo67 cvo68 cvo69 cvo70 cvo71 cvo72 cvo73 cvo74 cvo75 c5a1 c5a2
> c5a3 c5a4 c5a5 c5a6 c5a7 c5a8 c5a9 c5b1 c5b2 c5b3 c5b4 c5b5 c5b6 c5b7 c5b8 c5
> b9 c5b10 c5c1 c5c2 c5c3 c5c4 c5c5 c5c6 c5c7 c5c8 c5c9 c5c10 c5c11 c5c12 c5c13
>  c5c14 c5c15 c5c16 c5c17 c5d1 c5d2 c5d3 c5d4 c5d5 c5d6 c5d7 c5d8 c5d9 c5d10 c
> 5d11 c5d12 c5d13 c5d14 c5d15 c5d16 c5e1 c5e2 c5e3 c5e4 c5e5 c5e6 c5e7 c5e8 c5
> e9 c5e10 c5e11 c5e12 c5e13 c5e14 c5e15 c5f1 c5f2 c5f3 c5f4 c5f5 c5f6 c5f7 c5f
> 8 c5f9 c5f10 c5f11 c5f12 c5f13 c5f14 c5f15 c5f16 c5f17 c5g1 c5g2 c5g3 c5g4 c5
> g5 c5g6 c5g7 c5g8 c5g9 c5g10 c5g11 c5g12 c5g13 c5g14 c5g15 c5g16 c5g17 c5g18
> c5g19 c5g20 c5g21 c5g22 c5g23 c5g24 c5g25 c5g26 c5g27 c5g28 c5h1 c5h2 c5h3 c5
> h4 c5h5 c5h6 c5h7 c5h8 c5h9 c5h10 c5h11 c5h12 c5h13 c5h14 c5h15 c5h16 c5h17 c
> 5h18 c5h19 c5h20 c5h21 c5h22 c5h23 c5h24 c5h25 c5h26 c5h27 c5i1 c5i2 c5i3 c5i
> 4 c5i5 c5i6 c5i7 c5i8 c5i9 c5i10 c5i11 c5i12 c5j1a c5j2a c5j3a c5j4a c5j5a c5
> j6a c5j7a c5j8a c5j9a c5j10a c5j11a c5j12a c5j13a c5j14a c5j15a c5j16a c5j17a
>  c5j18a c5j19a c5j20a c5j21a c5j22a c5j23a c5j24a c5j25a c5j26a c5j27a c5j28a
>  c5j29a c5j30a c5j31a c5j32a c5j33a c5j34a c5j35a c5j36a c5j37a c5j38a c5j39a
>  c5j40a c5j41a c5j42a c5j43a c5j44a c5j45a c5j46a c5j47a c5j1b c5j2b c5j3b c5
> j4b c5j5b c5j6b c5j7b c5j8b c5j9b c5j10b c5j11b c5j12b c5j13b c5j14b c5j15b c
> 5j16b c5j17b c5j18b c5j19b c5j20b c5j21b c5j22b c5j23b c5j24b c5j25b c5j26b c
> 5j27b c5j28b c5j29b c5j30b c5j31b c5j32b c5j33b c5j34b c5j35b c5j36b c5j37b c
> 5j38b c5j39b c5j40b c5j41b c5j42b c5j43b c5j44b c5j45b c5j46b c5j47b c5k1 c5k
> 2 c5k3 c5k4 c5k5 c5k6 c5k7 c5k8 c5k9 c5k10 c5k11  c5k12 c5k13 c5k14 c5k15 c5k
> 16 c5k17 c5k18 c5k19 c5k20 c5k21 c5k22 c5k23 c5k24 c5k25 c5k26 c5k27 c5k28 c5
> k29 c5k30 c5k31 c5k32 c5k33 c5k34 c5k35 c5k36 c5k37 c5k38 c5k39 c5k40 c5k41 c
> 5k42 c5k43 c5k44 c5k45 c5k46 c5k47 c5k48 c5k49 c5l1 c5l2 c5l3 c5l4 c5l5 c5l6
> c5l7 c5l8 c5l9 c5l10 c5l11 c5l12 c5l13 c5l14 c5l15 c5l16 c5l17 c5l18 c5l19 c5
> l20 c5l21 c5l22 c5l23 c5l24 c5l25 c5l26 c5m1 c5m2 c5m3 c5m4 c5m5 c5m6 c5m7 c5
> m8 c5m9 c5m10 c5m11 c5m12 c5m13 c5m14 c5m15 c5m16 c5m17 c5m18 c5m19 c5m20 c5m
> 21 c5m22 c5m23 c5m24 c5m25 c5n1 c5n2 c5n3 c5n4 c5n5 c5n6 c5n7 c5n8 c5n9 c5n10
>  c5n11 c5n12 c5n13 c5n14 c5n15 c5n16 c5n17 c5n18 c5n19 c5n20 c5n21 c5n22 c5o1
>  c5o2 c5o3 c5o4 c5o5 c5o6 c5o7 c5o8 c5o9 c5o10 c5o11 c5o12 c5o13 c5o14 c5o15
> c5o16 c5o17 c5o18 c5o19 c5o20 c5o21 c5o22 c5p1 c5p2 c5p3 c5p4 c5p5 c5p6 c5p7
> c5p8 c5p9 c5p10 c5p11 c5p12 c5p13 c5p14 c5p15 c5p16 c5p17 c5p18 c5p19 c5p20 c
> 5p21 c5q1 c5q2 c5q3 c5q4 c5q5 c5q6 c5q7 c5q8 c5q9 c5q10 c5q11 c5q12 c5q13 c5q
> 14 c5q15 c5q16 c5q17 c5q18 c5q19 c5q20 c5q21 c5q22 c5q23 c5q24 c5q25 c5q26 c5
> q27 c5q28 c5q29 c5q30 c5r1 c5r2 c5r3 c5r4 c5r5 c5r6 c5r7 c5r8 c5r9 c5r10 c5r1
> 1 c5r12 c5r13 c5r14 c5r15 c5s1 c5s2 c5s3 c5s4 c5s5 c5s6 c5s7 c5s8 c5s9 c5s10
> c5t1 c5t2 c5t3 c5t4 c5t5 c5t6 c5t7 c5t8 c5t9 c5t10 c5t11 c5t12 c5t13 c5t14 c5
> t15 c5t16 c5t17 c5t18 c5t19 c5t20 c5t21 c5t22 c5t23 c5u1 c5u2 c5u3 c5u4 c5u5
> c5u6 c5u7 c5u8 c5u9 c5u10 c5u11 c5u12 c5u13 c5u14 c5u15 c5u16 c5u17 c5u18 c6_
> 2 c6_3a c6_3b c6_4a c6_4b c6_5 c6_6a c6_6b c6_6c c6_7 c6_8 c6_9 c6_10 c6_11 c
> 6_12 c6_13 c6_14 c6_15 c6_16 c6_17 c6_18 c6_19 c7a1 c7a2 c7a3 c7a4 c7a5 c7a6
> c7a7 c7a8 c7a9 c7a10 c7a11 c7a12 c7a13 c7a14 c7a15 c7a16 c7a17 c7a18 c7a19 c7
> a20 c7a21 c7a22 c7a23 c7a24 c7a25 c7a26 c7a27 c7a28 c7a29 c7a30 c7a31 c7a32 c
> 7a33 c7a34 c7a35 c7a36 c7a37 c7a38 c7a39 c7a40 c7a41 c7a42 c7a43 c7a44 c7a45
> c7a46 c7a47 c7a48 c7a49 c7a50 c7a51 c7a52 c7a53 c7a54 c7a55 c7a56 c7a57 c7a58
>  c7a59 c7a60 c7a61 c7a62 c7a63 c7a64 c7a65 c7a66 c7a67 c7a68 c7a69 c7a70 c7a7
> 1 c7a72 c7a73 c7a74 c7a75 c7a76 c7a77 c7a78 c7a79 c7a80 c7a81 c7a82 c7a83 c7a
> 84 c7a85 c7a86 c7a87 c7a88 c7a89 c7a90 c7a91 c7a92 c7a93 c7a94 c7a95 c7a96 c7
> a97 c7a98 c7a99 c7a100 c7b1 c7b2 c7b3 c7b4 c7b5 c7b6 c7b7 c7b8 c7b9 c7b10 c7b
> 11 c7b12 c7b13 c7b14 c7b15 c7b16 c7b17 c7b18 c7b19 c7b20 c7b21 c7b22 c7b23 c7
> b24 c7b25 c7b26 c7b27 c7b28 c7b29 c7b30 c7b31 c7b32 c7b33 c7b34 c7b35 c7b36 c
> 7b37 c7b38 c7b39 c7b40 c7b41 c7b42 c7b43 c7b44 c7b45 c7b46 c7b47 c7b48 c7b49
> c7b50 c7b51 c7b52 c7b53 c7b54 c7b55 c7b56 c7b57 c7b58 c7b59 c7b60 c7b61 c7b62
>  c7b63 c7b64 c7b65 c7b66 c7b67 c7b68 c7b69 c7b70 c7b71 c7b72 c7b73 c7b74 c7b7
> 5 c7b76 c7b77 c7b78 c7b79 c7b80 c7b81 c7b82 c7b83 c7b84 c7b85 c7b86 c7b87 c7b
> 88 c7b89 c7b90 c7b91 c7b92 c7b93 c7b94 c7b95 c7b96 c7b97 c7b98 c7b99 c7b100 e
> 1 e2 e3 e4 e5 e6 e7 e8 e9 e10 e11 e12 e13 e14 e15 e16

.
. cd"C:\Users\scott\Desktop\Stata data and do\BCS\BCS Sweep 26\stata\stata11"
C:\Users\scott\Desktop\Stata data and do\BCS\BCS Sweep 26\stata\stata11

.
. merge 1:1 bcsid using bcs96x.dta
(variable q39_1 was byte, now double to accommodate using data's values)
(variable q39_2 was byte, now double to accommodate using data's values)
(label q39_2 already defined)
(label q39_1 already defined)

    Result                      Number of obs
    -----------------------------------------
    Not matched                         6,330
        from master                     4,471  (_merge==1)
        from using                      1,859  (_merge==2)

    Matched                             7,144  (_merge==3)
    -----------------------------------------

. drop _merge

.

In [19]:
%%stata

gen econac=. 
replace econac=1 if(b960259==1)
replace econac=2 if(b960260==1)
replace econac=1 if(b960261==1)
replace econac=2 if(b960262==1)
replace econac=3 if(b960263==1)
replace econac=4 if(b960264==1)
replace econac=5 if(b960265==1)
replace econac=5 if(b960266==1)

label define econac_lbl 1"FT employment" 2"PT employment" 3"Unemployed" 4"FT Education" 5"Out of Labour Force" 
label value econac econac_lbl

tab econac

.
. gen econac=.
(13,474 missing values generated)

. replace econac=1 if(b960259==1)
(6,035 real changes made)

. replace econac=2 if(b960260==1)
(693 real changes made)

. replace econac=1 if(b960261==1)
(533 real changes made)

. replace econac=2 if(b960262==1)
(97 real changes made)

. replace econac=3 if(b960263==1)
(395 real changes made)

. replace econac=4 if(b960264==1)
(307 real changes made)

. replace econac=5 if(b960265==1)
(31 real changes made)

. replace econac=5 if(b960266==1)
(148 real changes made)

.
. label define econac_lbl 1"FT employment" 2"PT employment" 3"Unemployed" 4"FT
> Education" 5"Out of Labour Force"

. label value econac econac_lbl

.
. tab econac

             econac |      Freq.     Percent        Cum.
--------------------+-----------------------------------
      FT employment |      6,463       80.39       80.39
      PT employment |        709        8.82       89.20
         Unemployed |        386        4.80       94.00
       FT Education |        303        3.77       97.77
Out of Labour Force |        179        2.23      100.00
--------------------+-----------------------------------
              Total |      8,040      100.00

.

Some interesting findings. We see around 80% going straight into work and around 5% going on to higher education. Unemployment of around 4%, with part time employment at 9%.  Comparing this with our previous dataset there are some rather obvious differences here. Though something to note is that thus far* we are comparing current (so 26 year old economic activity) with the first 12 months of economic activity from the NCDS dataset. 

*This will be changed and added in with the first 12 months and last 12 months for better comparison.

In [20]:
%%stata

gen obin=.
replace obin=0 if (b960154==1)
replace obin=0 if (b960154==2)
replace obin=0 if (b960154==3)
replace obin=0 if (b960154==4)
replace obin=1 if (b960154==5)
replace obin=1 if (b960154==6)
replace obin=1 if (b960154==7)
replace obin=1 if (b960154==8)
replace obin=1 if (b960154==9)
replace obin=1 if (b960154==10)
replace obin=1 if (b960154==11)
replace obin=1 if (b960154==12)
replace obin=1 if (b960154==13)
replace obin=1 if (b960154==14)
replace obin=1 if (b960154==15)

label define obin_lbl 0"<5 O-Level Passes" 1"5 or More O-Level Passes" 
label value obin obin_lbl

tab obin

.
. gen obin=.
(13,474 missing values generated)

. replace obin=0 if (b960154==1)
(637 real changes made)

. replace obin=0 if (b960154==2)
(587 real changes made)

. replace obin=0 if (b960154==3)
(435 real changes made)

. replace obin=0 if (b960154==4)
(412 real changes made)

. replace obin=1 if (b960154==5)
(436 real changes made)

. replace obin=1 if (b960154==6)
(377 real changes made)

. replace obin=1 if (b960154==7)
(387 real changes made)

. replace obin=1 if (b960154==8)
(438 real changes made)

. replace obin=1 if (b960154==9)
(405 real changes made)

. replace obin=1 if (b960154==10)
(240 real changes made)

. replace obin=1 if (b960154==11)
(136 real changes made)

. replace obin=1 if (b960154==12)
(46 real changes made)

. replace obin=1 if (b960154==13)
(17 real changes made)

. replace obin=1 if (b960154==14)
(5 real changes made)

. replace obin=1 if (b960154==15)
(1 real change made)

.
. label define obin_lbl 0"<5 O-Level Passes" 1"5 or More O-Level Passes"

. label value obin obin_lbl

.
. tab obin

                    obin |      Freq.     Percent        Cum.
-------------------------+-----------------------------------
       <5 O-Level Passes |      2,071       45.43       45.43
5 or More O-Level Passes |      2,488       54.57      100.00
-------------------------+-----------------------------------
                   Total |      4,559      100.00

.

In [21]:
%%stata

gen educur=.
replace educur=0 if (econac==1)
replace educur=0 if (econac==2)
replace educur=0 if (econac==3)
replace educur=1 if (econac==4)
replace educur=0 if (econac==5)

label define educur_lbl 0"Not In Education" 1"In Education"
label value educur educur_lbl

tab educur

tab2 obin educur

.
. gen educur=.
(13,474 missing values generated)

. replace educur=0 if (econac==1)
(6,463 real changes made)

. replace educur=0 if (econac==2)
(709 real changes made)

. replace educur=0 if (econac==3)
(386 real changes made)

. replace educur=1 if (econac==4)
(303 real changes made)

. replace educur=0 if (econac==5)
(179 real changes made)

.
. label define educur_lbl 0"Not In Education" 1"In Education"

. label value educur educur_lbl

.
. tab educur

          educur |      Freq.     Percent        Cum.
-----------------+-----------------------------------
Not In Education |      7,737       96.23       96.23
    In Education |        303        3.77      100.00
-----------------+-----------------------------------
           Total |      8,040      100.00

.
. tab2 obin educur

-> tabulation of obin by educur

                      |        educur
                 obin | Not In Ed  In Educat |     Total
----------------------+----------------------+----------
    <5 O-Level Passes |     1,818         72 |     1,890
5 or More O-Level Pas |     2,253        137 |     2,390
----------------------+----------------------+----------
                Total |     4,071        209 |     4,280

.

In [22]:
%%stata

logit obin i.educur, or

coefplot, vertical drop(_cons) 

margins i.educur

margins r.educur

.
. logit obin i.educur, or

Iteration 0:   log likelihood = -2937.3975
Iteration 1:   log likelihood = -2933.1129
Iteration 2:   log likelihood = -2933.1077
Iteration 3:   log likelihood = -2933.1077

Logistic regression                                     Number of obs =  4,280
                                                        LR chi2(1)    =   8.58
                                                        Prob > chi2   = 0.0034
Log likelihood = -2933.1077                             Pseudo R2     = 0.0015

------------------------------------------------------------------------------
        obin | Odds ratio   Std. err.      z    P>|z|     [95% conf. interval]
-------------+----------------------------------------------------------------
      educur |
In Educat..  |   1.535397   .2286766     2.88   0.004     1.146689     2.05587
       _cons |   1.239274   .0390697     6.80   0.000     1.165017    1.318264
------------------------------------------------------------------------------
Note: _cons estimates baseline odds.

.
. coefplot, vertical drop(_cons)

.
. margins i.educur

Adjusted predictions                                     Number of obs = 4,280
Model VCE: OIM

Expression: Pr(obin), predict()

------------------------------------------------------------------------------
             |            Delta-method
             |     Margin   std. err.      z    P>|z|     [95% conf. interval]
-------------+----------------------------------------------------------------
      educur |
Not In Ed..  |   .5534267   .0077916    71.03   0.000     .5381554    .5686979
In Educat..  |   .6555024   .0328706    19.94   0.000     .5910773    .7199275
------------------------------------------------------------------------------

.
. margins r.educur

Contrasts of adjusted predictions                        Number of obs = 4,280
Model VCE: OIM

Expression: Pr(obin), predict()

------------------------------------------------
             |         df        chi2     P>chi2
-------------+----------------------------------
      educur |          1        9.13     0.0025
------------------------------------------------

--------------------------------------------------------------------
                   |            Delta-method
                   |   Contrast   std. err.     [95% conf. interval]
-------------------+------------------------------------------------
            educur |
    (In Education  |
               vs  |
Not In Education)  |   .1020757   .0337814      .0358654     .168286
--------------------------------------------------------------------

.

In [23]:
%%stata

gen sex1=.
replace sex1=0 if (sex86==1)
replace sex1=1 if (sex86==2)

label define sex1_lbl 0"Female" 1"Male"
label value sex1 sex1_lbl

gen ethnic=.
replace ethnic=0 if (oa3_1==1)
replace ethnic=0 if (oa3_1==2)
replace ethnic=0 if (oa3_1==3)
replace ethnic=1 if (oa3_1==4)
replace ethnic=1 if (oa3_1==5)
replace ethnic=1 if (oa3_1==6)
replace ethnic=1 if (oa3_1==7)
replace ethnic=1 if (oa3_1==8)

label define ethnic_lbl 0"White" 1"Non-White"
label value ethnic ethnic_lbl

gen fclas=.
replace fclas=1 if (t11_2==1)
replace fclas=2 if (t11_2==2)
replace fclas=3 if (t11_2==3)
replace fclas=4 if (t11_2==4)
replace fclas=5 if (t11_2==5)
replace fclas=6 if (t11_2==6)

label define clas_lbl 1"I" 2"II" 3"III Non-manual" 4"III Manual" 5"IV" 6"V" 
label value fclas clas_lbl

.
. gen sex1=.
(13,474 missing values generated)

. replace sex1=0 if (sex86==1)
(5,815 real changes made)

. replace sex1=1 if (sex86==2)
(5,800 real changes made)

.
. label define sex1_lbl 0"Female" 1"Male"

. label value sex1 sex1_lbl

.
. gen ethnic=.
(13,474 missing values generated)

. replace ethnic=0 if (oa3_1==1)
(8,957 real changes made)

. replace ethnic=0 if (oa3_1==2)
(26 real changes made)

. replace ethnic=0 if (oa3_1==3)
(23 real changes made)

. replace ethnic=1 if (oa3_1==4)
(74 real changes made)

. replace ethnic=1 if (oa3_1==5)
(133 real changes made)

. replace ethnic=1 if (oa3_1==6)
(72 real changes made)

. replace ethnic=1 if (oa3_1==7)
(15 real changes made)

. replace ethnic=1 if (oa3_1==8)
(85 real changes made)

.
. label define ethnic_lbl 0"White" 1"Non-White"

. label value ethnic ethnic_lbl

.
. gen fclas=.
(13,474 missing values generated)

. replace fclas=1 if (t11_2==1)
(511 real changes made)

. replace fclas=2 if (t11_2==2)
(1,888 real changes made)

. replace fclas=3 if (t11_2==3)
(653 real changes made)

. replace fclas=4 if (t11_2==4)
(2,567 real changes made)

. replace fclas=5 if (t11_2==5)
(594 real changes made)

. replace fclas=6 if (t11_2==6)
(153 real changes made)

.
. label define clas_lbl 1"I" 2"II" 3"III Non-manual" 4"III Manual" 5"IV" 6"V"

. label value fclas clas_lbl

.

In [24]:
%%stata

tab2 educur sex1
tab2 educur ethnic
tab2 educur fclas

.
. tab2 educur sex1

-> tabulation of educur by sex1

                 |         sex1
          educur |    Female       Male |     Total
-----------------+----------------------+----------
Not In Education |     2,980      3,189 |     6,169
    In Education |       114        118 |       232
-----------------+----------------------+----------
           Total |     3,094      3,307 |     6,401

. tab2 educur ethnic

-> tabulation of educur by ethnic

                 |        ethnic
          educur |     White  Non-White |     Total
-----------------+----------------------+----------
Not In Education |     4,975        124 |     5,099
    In Education |       166         15 |       181
-----------------+----------------------+----------
           Total |     5,141        139 |     5,280

. tab2 educur fclas

-> tabulation of educur by fclas

                 |                    fclas
          educur |         I         II  III Non-m  III Manua |     Total
-----------------+--------------------------------------------+----------
Not In Education |       348      1,247        428      1,546 |     3,980
    In Education |        19         57         12         40 |       142
-----------------+--------------------------------------------+----------
           Total |       367      1,304        440      1,586 |     4,122


                 |         fclas
          educur |        IV          V |     Total
-----------------+----------------------+----------
Not In Education |       327         84 |     3,980
    In Education |        13          1 |       142
-----------------+----------------------+----------
           Total |       340         85 |     4,122

.

In [25]:
%%stata

logit obin i.educur i.sex1 i.ethnic i.fclas, or

.
. logit obin i.educur i.sex1 i.ethnic i.fclas, or

Iteration 0:   log likelihood = -1461.6852
Iteration 1:   log likelihood = -1372.1689
Iteration 2:   log likelihood = -1371.3688
Iteration 3:   log likelihood = -1371.3668
Iteration 4:   log likelihood = -1371.3668

Logistic regression                                     Number of obs =  2,187
                                                        LR chi2(8)    = 180.64
                                                        Prob > chi2   = 0.0000
Log likelihood = -1371.3668                             Pseudo R2     = 0.0618

------------------------------------------------------------------------------
        obin | Odds ratio   Std. err.      z    P>|z|     [95% conf. interval]
-------------+----------------------------------------------------------------
      educur |
In Educat..  |   1.575429   .3796199     1.89   0.059     .9824053    2.526427
             |
        sex1 |
       Male  |   1.065141    .098215     0.68   0.494     .8890352     1.27613
             |
      ethnic |
  Non-White  |   .8640771   .2698247    -0.47   0.640     .4685419    1.593517
             |
       fclas |
         II  |   .5252764   .0982245    -3.44   0.001     .3640967    .7578078
III Non-m..  |   .4127439   .0900827    -4.05   0.000     .2690935    .6330794
 III Manual  |   .1911169   .0356233    -8.88   0.000     .1326292    .2753969
         IV  |   .1767966   .0426812    -7.18   0.000     .1101492    .2837697
          V  |   .0791051   .0336472    -5.96   0.000     .0343675    .1820797
             |
       _cons |   4.351044   .7712504     8.30   0.000     3.074061    6.158492
------------------------------------------------------------------------------
Note: _cons estimates baseline odds.

.

This logistic regression model depicts that individuals who are in Education, men, and ethnic minorities are not statistically signficicant. Interestingly there is a very apparent trend looking at fathers social class. There is a significant downward trend when comparing professional social class to others that shows those on the lower end of the social class hierarchy have worse odds in comparison to the sons of professionals in obtaining 5 or more O-level passes. For example at the two extremes, In comparison to fathers social class I, II has a 0.53 times the odd of obtaining 5 or more O-level passes. Now looking at the comparison between fathers social class I and V, V has a 0.08 times the odd of obtaining 5 or more O-level passes.

In [26]:
%%stata

coefplot, vertical drop(_cons) keep(*.fclas)

.
. coefplot, vertical drop(_cons) keep(*.fclas)

.


Do same with other dataset. 

Write up report.

Write up about synthetic cohorts. 

Write up on missing data. 

Finish off Lit review.